# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.destroy_all 

paul, alia, leto = User.create([
  {name: 'Paul Atreides',  email: 'paul@arrakis.com', password: 'ironhack', password_confirmation: 'ironhack'},
  {name: 'Alia Atreides',  email: 'alia@arrakis.com',  password: 'ironhack', password_confirmation: 'ironhack'},
  {name: 'Leto Atreides', email: 'leto@arrakis.com',  password: 'ironhack', password_confirmation: 'ironhack'}
])

Author.destroy_all 
Artwork.destroy_all

picasso = Author.create(name: "Pablo Picasso", bio: 'Not only was Pablo Picasso one of the most influential painters and artist of his time, he is also one of the most recognized figures of the 20th century, thanks to the work he created during his career. Born in Malaga, Spain, in October of 1881, he was the first child born in the family. His father worked as an artist, and was also a professor at the school of fine arts; he also worked as a curator for the museum in Malaga.' , image_url: 'https://upload.wikimedia.org/wikipedia/commons/9/98/Pablo_picasso_1.jpg', born_in: 1881 , died_in: 1973 )
rothko = Author.create(name: "Mark Rothko", bio: 'Mark Rothko was born Marcus Rothkowitz in Dvinsk, Russia (now Daugavpils, Latvia), on September 25, 1903, and immigrated to the United States with his family in his youth. In the mid-20th century, he belonged to a circle of New York-based artists (also including Willem de Kooning and Jackson Pollock) who became known as the Abstract Expressionists. His signature works, large-scale paintings of luminous colored rectangles, used simplified means to evoke emotional responses. Rothko committed suicide on February 25, 1970.' , image_url: 'http://a5.files.biography.com/image/upload/c_fill,cs_srgb,dpr_1.0,g_face,h_300,q_80,w_300/MTE5NDg0MDU1MTE3MzM0MDMx.jpg', born_in: 1903 , died_in: 1970 )
pollock = Author.create(name: "Jackson Pollock", bio: 'Born on January 28, 1912, in Cody, Wyoming, artist Jackson Pollock studied under Thomas Hart Benton before leaving traditional techniques to explore abstraction expressionism via his splatter and action pieces, which involved pouring paint and other media directly onto canvases. Pollock was both renowned and critiqued for his conventions. He died after driving drunk and crashing into a tree in New York in 1956, at age 44.' , image_url: 'http://a5.files.biography.com/image/upload/c_fit,cs_srgb,dpr_1.0,q_80,w_620/MTE5NTU2MzE2MzQ3NDY3Mjc1.jpg', born_in: 1912 , died_in: 1956 )
mondrian = Author.create(name: "Piet Mondrian", bio: 'Dutch painter Piet Mondrian began his career firmly rooted in the representational form, favoring naturalistic and impressionistic landscapes. His style was influenced by Picasso and Braque as it morphed into his signature non-representational form which he termed Neo-Plasticism. It was through this form that he became an important contributor to the De Stijl art movement.' , image_url: 'http://a2.files.biography.com/image/upload/c_fill,cs_srgb,dpr_1.0,g_face,h_300,q_80,w_300/MTE1ODA0OTcxNzI2MzA4ODc3.jpg', born_in: 1872 , died_in: 1944 )
bacon = Author.create(name: "Francis Bacon", bio: 'Francis Bacon was born to English parents living in Dublin, Ireland, on November 28, 1909. After traveling to Germany and France as a young man, he settled in London and began a career as a self-taught artist. Most of his paintings from the 1940s to \'60s depict the human figure in scenes that suggest alienation, violence and suffering. Bacon\'s provocative, expressive work is considered some of the most important art of the postwar era. He died in Madrid, Spain, on April 28, 1992.' , image_url: 'http://a1.files.biography.com/image/upload/c_fill,cs_srgb,dpr_1.0,g_face,h_300,q_80,w_300/MTE1ODA0OTcyMDgzODczMjkz.jpg', born_in: 1909 , died_in: 1992 )


thedream = picasso.artworks.create(last_price: 25, ipo_price: 25, status:"Offering", name:'The dream', description: 'Le Rêve (The Dream in French) is a 1932 oil painting (130 × 97 cm) by Pablo Picasso, then 50 years old, portraying his 24-year-old mistress Marie-Thérèse Walter. It is said to have been painted in one afternoon, on January 24, 1932. It belongs to Picasso\'s period of distorted depictions, with its oversimplified outlines and contrasted colors resembling early Fauvism.
The erotic content of the painting has been noted repeatedly, with critics pointing out that Picasso painted an erect penis, presumably symbolizing his own, in the upturned face of his model.

Le Rêve was purchased for $7,000 in 1941 by Victor and Sally Ganz of New York City. This purchase began their 50-year collection of works by just five artists: Picasso, Jasper Johns, Robert Rauschenberg, Frank Stella, and Eva Hesse. After the Ganzes died (Victor in 1987 and Sally in 1997), their collection, including Le Rêve, was sold at Christie\'s auction house on November 11, 1997. Le Rêve sold for an unexpectedly high $48.4 million, at the time the sixth most expensive painting sold (tenth when taking inflation into account). The entire collection set a record for the sale of a private collection, bringing $206.5 million. The total amount paid by the Ganzes over their lifetime of collecting these pieces was around $2 million.

The buyer who purchased Le Rêve at Christie\'s in 1997 appears to have been the Austrian-born investment fund manager Wolfgang Flöttl, who also briefly held Van Gogh\'s Portrait of Dr. Gachet in possession in the late 1990s. In 2001, under financial pressure, he sold Le Rêve to casino magnate Steve Wynn for an undisclosed sum, estimated to be about $60 million.', year: 1932, outstanding_shares: 1000000, image_url: 'http://www.pablopicasso.org/images/paintings/the-dream.jpg')

demoisellesdavignon = picasso.artworks.create(last_price: 30, ipo_price: 30, status:"Trading", name:'Les demoiselles d\'Avignon', description: 'Les Demoiselles d’Avignon marks a radical break from traditional composition and perspective in painting. It depicts five naked women with figures composed of flat, splintered planes and faces inspired by Iberian sculpture and African masks. The compressed space the figures inhabit appears to project forward in jagged shards; a fiercely pointed slice of melon in the still life of fruit at the bottom of the composition teeters on an impossibly upturned tabletop. These strategies would be significant in Picasso’s subsequent development of Cubism, charted in this gallery with a selection of the increasingly fragmented compositions he created in this period.

Picasso unveiled the monumental painting in his Paris studio after months of revision. The Avignon of the work’s title is a reference to a street in Barcelona famed for its brothel. In Picasso’s preparatory studies for the work, the figure at the left was a man, but the artist eliminated this anecdotal detail in the final painting.', year: 1907, outstanding_shares: 1000000, image_url: 'http://resources.saylor.org.s3.amazonaws.com/ARTH/ARTH111/ARTH111-9.1-LesDemoisellesdAvignon-Smarthistory-CCBYNCSA_files/avignon.jpg')

doramar = picasso.artworks.create(last_price: 50, ipo_price: 50, status:"Trading", name:'Dora Maar au Chat', description: 'Dora Maar au Chat by Pablo Picasso was painted in 1941 during the Second World War, during a difficult period as France was, at that time, occupied by Nazi Germany. The painting depicts Dora Maar, Picasso’s lover, sitting in a chair and there is a small cat sitting on her shoulders. While such is a simple theme for a painting, it is has the honor of being one of the most expensive paintings in the world. This particular portrait is one of many that Picasso painted during his ten year relationship with Dora Maar, which began when Picasso was fifty five years old. The portrait was obtained by Lee and Mary Block, art collectors from Chicago, very shortly after it was painted and was sold at auction for $95,216,000 in 2006.', year: 1941, outstanding_shares: 1000000, image_url: 'http://c300221.r21.cf1.rackcdn.com/dora-maar-au-chat-1345868955_b.jpg')

garsonalapipe = picasso.artworks.create(last_price: 42, ipo_price: 42, status:"Offering", name:'Garçon à la pipe', description: 'Garçon à la Pipe (English: Boy with a Pipe) is a painting by Pablo Picasso. It was painted in 1905 when Picasso was 24 years old, during his Rose Period, soon after he settled in the Montmartre section of Paris, France. The oil on canvas painting depicts a Parisian boy holding a pipe in his left hand and wearing a garland or wreath of flowers.', year: 1905, outstanding_shares: 1000000, image_url: 'http://www.galleryintell.com/wp-content/uploads/2014/02/Picasso-Gar%C3%A7on-%C3%A0-la-Pipe-1905.jpg')

fourdarksinred = rothko.artworks.create(last_price: 20, ipo_price: 20, status:"Trading", name:'Four Darks in Red', description: 'In 1969, Rothko exhibited ten paintings at the Sidney Janis Gallery; Four Darks in Red were among those shown. With its dark, restricted palette, the picture exemplifies Rothko\'s late-period gravitation towards reds and browns. It established a prototype for the dark red/brown/black palette and horizontal composition that he would later use in the uninstalled Seagram Building paintings. Although the imagery of pictures like Four Darks in Red seems far distant from that of Slow Swirl at the Edge of the Sea (1944), Rothko believed that the rectangles merely offered a new way of representing the presences or spirits that he tried to capture in those earlier works. "It was not that the figure had been removed," he once said, "..but the symbols for the figures... These new shapes say.. what the figures said." In this way, Rothko imagined a kind of direct communion between himself and the viewer, one which might touch the viewer with a higher spirituality.', year: 1958, outstanding_shares: 1000000, image_url: 'https://upload.wikimedia.org/wikipedia/en/b/b9/RothkoFourDarksRed.jpg')

n10 = rothko.artworks.create(last_price: 20, ipo_price: 20, status:"Trading", name:'No 10', description: 'The irregular patches of color characteristic of the artist’s Multiform paintings of 1948 seem to have settled into place on this canvas, which Rothko divided horizontally into three dominant planes of color that softly and subtly merge into one another. Between 1949 and 1950 Rothko simplified the compositional structure of his paintings and arrived at this, his signature style. He explained, "The progression of a painter\'s work, as it travels in time from point to point, will be toward clarity: toward the elimination of all obstacles between the painter and the idea, and between the idea and the observer." MoMA acquired No. 10 in 1952. The painting—the first by Rothko to enter the collection—was so radical for the time that a trustee of the Museum resigned in protest.', year: 1950, outstanding_shares: 1000000, image_url: 'http://www.reproduction-gallery.com/oil_painting_reproduction_gallery/Mark-Rothko-no-10-1950-large-1030408292.jpg')

n1 = rothko.artworks.create(last_price: 20, ipo_price: 20, status:"Trading", name:'No 1, Royal Red and Blue', description: 'No 1 Royal Red and Blue received one of the larger prices when in auction in 2012 at Sotheby’s. The price tag of $75m represents the popularity of the artist’s original paintings, as well as the relative prominence of this particular piece with in his career.', year: 1954, outstanding_shares: 1000000, image_url: 'http://uploads1.wikiart.org/images/mark-rothko/no-1-royal-red-and-blue-1954.jpg')

convergence = pollock.artworks.create(last_price: 20, ipo_price: 20, status:"Trading", name:'Jason Pollock', description: 'Perhaps his most famous work was a painting entitled Convergence, which was a collage of colors splattered on a canvas that created masterful shapes and lines that evoke emotions and attack the eye. The painting was created in 1952, and is oil on canvas; 93.5 inches by 155 inches (Karmel, 1999). With Pollock\'s brushstrokes he was able to make handy use of colors, lines, textures, lights, and contrasting shapes. This painting is enormous and its size can only really be appreciated in person. In 1964, puzzle producing company, Springbok Editions, released Convergence (Inspired by Pollock\'s painting) the jigsaw puzzle. It was a 340-piece puzzle that they promoted as "the world\'s most difficult puzzle". The impact of Pollock\'s Convergence was evident in 1965 when hundreds of thousands of Americans purchased the jigsaw puzzle. ', year: 1952, outstanding_shares: 1000000, image_url: 'http://www.jackson-pollock.org/images/paintings/convergence.jpg')

one31 = pollock.artworks.create(last_price: 20, ipo_price: 20, status:"Trading", name:'One: Number 31', description: 'One: Number 31, 1950 is a masterpiece of the "drip" technique and among the largest of Pollock\'s paintings. Begun approximately three years after his first painting in this style, the work is evidence of the artist\'s skill and technical prowess. Calligraphic, looping cords of color animate and energize every inch of the composition, which seems to expand visually, despite its already enormous size. As he did for all his drip paintings, Pollock painted One: Number 31, 1950 with the canvas lying on the floor. ', year: 1950, outstanding_shares: 1000000, image_url: 'http://www.jackson-pollock.org/images/paintings/one-number31.jpg')

numberone = pollock.artworks.create(last_price: 20, ipo_price: 20, status:"Trading", name:'Number One', description: 'Jackson Pollock\'s mural-size "drip" paintings met with mixed reactions when they debuted at the Betty Parsons Gallery in New York City in 1948. Sales were dismal, and critical reviews offered skepticism or mild appreciation. Yet only one year later, a Life magazine article featured Pollock, arms crossed and cigarette dangling from his lips, standing in front of one of his swirled, caffeinated images. The caption under the photograph asked, "Is he the greatest living painter in the United States?"

Number One, 1949 embodies the artistic breakthrough Pollock reached between 1947 and 1950. It was painted in an old barn-turned-studio next to a small house on the East End of Long Island, where Pollock lived and worked from 1945 on. The property led directly to Accabonac Creek, where eelgrass marshes and gorgeous, watery light were a source of inspiration for him. ', year: 1950, outstanding_shares: 1000000, image_url: 'http://www.jackson-pollock.org/images/paintings/number-one.jpg')

fullfathom = pollock.artworks.create(last_price: 20, ipo_price: 20, status:"Trading", name:'Full Fathom Five', description: 'Full Fathom Five is one of the earliest masterpieces of Pollock\'s drip technique. The actual origins and initial development of this technique have never been fully explained, except by reading back from fuller photographic evidence produced about 1950, two or three years after this work was painted. Like other practical breakthroughs in twentieth-century painting, "creative accident" seems likely to have played an important part, as Pollock probed and tested methods of paint application which promote the continuousness of line rather than the broken lines inevitable in the constant reloadings and readjustments of conventional brushwork. His solution was to pour from a can of domestic paint along a stick resting inside the container, so that a constant "beam" of pigment came into contact with the canvas (which he left unstretched on the studio floor). The character of the line was determined by certain physical and material variables that could be combined in almost infinite permutations: the viscosity of the paint (controlled by thinning and dilution); the angle and hence speed of the pouring; and the dynamics of Pollock\'s bodily gestures, his sweep and rhythm, especially in the wrist, arm and shoulder. "Like a seismograph", noted writer Wemer Haftmann "the painting recorded the energies and states of the man who drew it." In addition Pollock would flick, splatter and dab subsidiary colors on to the dominant linear configuration. ', year: 1947, outstanding_shares: 1000000, image_url: 'http://www.jackson-pollock.org/images/paintings/full-fathom-five.jpg')

mural = pollock.artworks.create(last_price: 20, ipo_price: 20, status:"Trading", name:'Mural', description: 'When Pollock painted Mural, he redefined not only the limits of his own abilities but also the possibilities of painting. Pollock\'s innovation provided a new direction for artist - he had combined the method of easel painting and an abstract style into the large scale of the traditional mural.

Mural was immediately recognized as a turning point for American art. Art critic Clement Greenberg had written encouraging but less than whole-hearted endorsements in his Pollock reviews, but, he said after he saw the big mural in Guggenheim\'s townhouse, "I took one look at it and I thought, "Now that\'s great art," and I knew Jackson was the greatest painter this country had produced." From this point on, throughout the forties, Greenberg was a firm advocate of Pollock\'s art, and in turn Pollock\'s success canonized Greenberg\'s judgment. ', year: 1943, outstanding_shares: 1000000, image_url: 'http://www.jackson-pollock.org/images/paintings/mural.jpg')

oval = mondrian.artworks.create(last_price: 20, ipo_price: 20, status:"Trading", name:'Composition in Oval', description: 'The geometry of this composition, made two years after Mondrian moved from Holland to Paris, is directly based on sketches of partially demolished buildings, with exposed floors, chimneys, and patches of wallpaper. Mondrian believed that horizontal and vertical lines, such as those he used here, expressed an underlying, universal order.', year: 1914, outstanding_shares: 1000000, image_url: 'https://rosswolfe.files.wordpress.com/2014/10/piet-mondrian-dutch-1872-1944-composition-in-oval-with-color-planes-1-1914-oil-on-canvas-42-38-x-3122-107-6-x-78-8-cm.jpg?w=872')

broadway = mondrian.artworks.create(last_price: 20, ipo_price: 20, status:"Trading", name:'Broadway Boogie Boogie', description: 'Mondrian, who had escaped to New York from Europe after the outbreak of World War II, delighted in the city\'s architecture. He was also fascinated by American jazz, particularly boogie-woogie, finding its syncopated beat, irreverent approach to melody, and improvisational aesthetic akin to what he called, in his own work, the "destruction of natural appearance; and construction through continuous opposition of pure means—dynamic rhythm." In this painting, his penultimate, Mondrian replaced the black grid that had long governed his canvases with predominantly yellow lines that intersect at points marked by squares of blue and red. These atomized bands of stuttering chromatic pulses, interrupted by light gray paths across the canvas suggesting the city\'s grid, the movement of traffic, and blinking electric lights, as well as the rhythms of jazz.', year: 1942, outstanding_shares: 1000000, image_url: 'http://www.piet-mondrian.org/images/paintings/broadway-boogie-woogie.jpg')

comporeblue = mondrian.artworks.create(last_price: 20, ipo_price: 20, status:"Trading", name:'Red and Blue', description: 'original date partly obliterated; mistakenly repainted 1925 by Mondrian', year: 1929, outstanding_shares: 1000000, image_url: 'http://c300221.r21.cf1.rackcdn.com/piet-mondrian-composition-no-ii-with-red-and-blue-1335455204_b.jpg')

compobrown = mondrian.artworks.create(last_price: 20, ipo_price: 20, status:"Trading", name:'Brown and Gray', description: '', year: 1913, outstanding_shares: 1000000, image_url: 'http://www.moma.org/collection_images/resized/155/app_zoom/CRI_151155.jpg')

popeinnocent = bacon.artworks.create(last_price: 20, ipo_price: 20, status:"Trading", name:'Portrait of Pope Innocent X', description: 'Although the figure in this picture derives from a 1650 portrait of Pope Innocent X by Diego Velazquez, Bacon avoided viewing the original painting,preferring to work from reproductions. Once again, he deploys a cage-like frame that surrounds the pope, but also introduces vertical brushing across the surface of the painting, an element he described as a curtain, relating the figure to a precious object requiring a protected space.However, the linear strokes are destructive to the image, and seem more like the bars of a jail cell. The lines almost seem to vibrate, and complementary shades of purple and yellow add to the tension of the composition. About his famous scream,Bacon says, "I didn\'t do it in the way that I wanted to.... I wanted to make the mouth, with its beauty of its color and everything, look like one of the sunsets or something of Monet."', year: 1953, outstanding_shares: 1000000, image_url: 'http://elusiv.com/arthistory/bacon/images/innocent.jpg')

crucifixion = bacon.artworks.create(last_price: 20, ipo_price: 20, status:"Trading", name:'Crucifixion', description: 'Crucifixion is the work that first launched Bacon into the public eye, long before the much greater successes of the post-war years. The painting may have been inspired by Rembrandt\'s Slaughtered Ox (c.1638), but also by Picasso\'s Surrealist style(perhaps sensing this latter connection, Herbert Read, in his book Art Now, illustrated Crucifixion adjacent to a Picasso Bather). The translucent whiteness painted over the bodily frame in Crucifixion adds a ghostly touch to an already unsettling composition,introducing Bacon\'s obsession with pain and fear. Exhibited at a time when the horrors of the First World War were still remembered, Crucifixion spoke of how brutality had changed the world forever. At the time of writing the picture is owned by Damien Hirst, an artist who has acknowledged a large debt to Bacon.', year: 1933, outstanding_shares: 1000000, image_url: 'http://www.francisbaconshop.com/include/images/products/gallery/gallery2Image_francis_bacon_mens_t_shirt_1348662740.jpg')

threestudies = bacon.artworks.create(last_price: 20, ipo_price: 20, status:"Trading", name:'Base of a Crucifixion', description: 'Three Studies launched Bacon\'s reputation in the mid 1940s and shows the importance of biomorphic Surrealism in forging his early style. Bacon may have originally intended to incorporate the figures in a crucifixion, but his reference to the base of such a composition suggests that he imagined them as part of a predella, the scenes at the bottom of a traditional altarpiece. The twisted bodies are all the more frightening for their vaguely familiar human-like forms, which appear to stretch out toward the viewer in pain and supplication. The perspective lines in the background create a shallow space,alluding to captivity and torture. The figures are based upon the Furies, goddesses of revenge from Greek mythology that play an important role in the Oresteia, a three-part tragedy by Aeschylus. Bacon may have been drawn to the play\'s themes of guilt and obsession. The piece profoundly influenced images of the body in post-war British art.', year: 1944, outstanding_shares: 1000000, image_url: 'https://upload.wikimedia.org/wikipedia/en/1/11/Three_Studies_for_Figures_at_the_Base_of_a_Crucifixion.jpg')

freud = bacon.artworks.create(last_price: 20, ipo_price: 20, status:"Trading", name:'Studies of Lucian Freud', description: '“The subject matter is very important for the Bacon market given the well documented camaraderie and rivalry he had with Lucian Freud,” Galbraith notes.  Given the rarity of the piece, the auction house will also feed the PR machine, drawing a crowd of clients and observers that creates a feedback loop that reinforces the importance of the auction and the piece, evidenced by the completely packed room at Christie’s on Tuesday.', year: 1969, outstanding_shares: 1000000, image_url: 'http://i.dailymail.co.uk/i/pix/2013/11/13/article-2504933-1960865100000578-493_634x380.jpg')
